### ISSUE TITLE
how to add this to  flow router ssr

### ISSUE THREAD

**Issue by sahanDissanayake** [kadirahq/meteor-dochead#15]
hello,

Is there a way to add this to this example http://flow-react-ssr.meteor.com/ ?

required way of function is when on the index page title will be a general one "Welcome"

But on the each other page the "Post title" will be the <title>

Any advise please ?

**Comment by arunoda** [comment]
Do you want to use DocHead with that demo repo?
If so easy.

Just use it inside a component or inside a action method of the Flow Router.

**Comment by sahanDissanayake** [comment]
Yes. I do wanna use it with the demo.

I'm happy with the result for "/" 

but when the URL is dynamic how do I get the dynamic data to change the <title> ?

Example:
http://flow-react-ssr.meteor.com/post/two The <title> for this page would be "MeteorHacks + Kadira => Kadira++" 

Do you get what I try to achieve ?
Thanks

**Comment by sahanDissanayake** [comment]
Yes. I do wanna use it with the demo.

I'm happy with the result for "/" 

but when the URL is dynamic how do I get the dynamic data to change the <title> ?

Example:
http://flow-react-ssr.meteor.com/post/two The <title> for this page would be "MeteorHacks + Kadira => Kadira++" 

Do you get what I try to achieve ?
Thanks

**Comment by sahanDissanayake** [comment]
Yes. I do wanna use it with the demo.

I'm happy with the result for "/" 

but when the URL is dynamic how do I get the dynamic data to change the "title" ?

Example:
http://flow-react-ssr.meteor.com/post/two The <title> for this page would be "MeteorHacks + Kadira => Kadira++" 

Do you get what I try to achieve ?
Thanks

**Comment by sahanDissanayake** [comment]
@arunoda  for example https://kadira.io/pricing

There is not "title" tag ? But the title does change when you click through the website links.. Are you changing it using pure JS ?

**Comment by sahanDissanayake** [comment]
@arunoda is there anything you could help me with for dynamic titles ?
Thanks
