### ISSUE TITLE
Version 1.3.0 breaks Safari compatibility

### ISSUE THREAD

**Issue by moooji** [kadirahq/meteor-dochead#18]
After updating to 1.3.0, I get the following error in the console. This happens in Safari 9.0 on OSX and iOS 9

TypeError: undefined is not an object (evaluating 'elements[key].parentNode.removeChild')
removeDocHeadAddedTagsboth.js:77
startupstartup_client.js:62
(anonymous function)flow_router.js:4
runTriggerstriggers.js:78
_actionHandlerouter.js:104
(anonymous function)client.browserify.js:569
nextEnterclient.browserify.js:401
dispatchclient.browserify.js:407
replaceclient.browserify.js:369
(anonymous function)router.js:381
startclient.browserify.js:265
pageclient.browserify.js:199
initializerouter.js:390
(anonymous function)_init.js:8
runStartupCallbacksstartup_client.js:29
readystartup_client.js:31

**Comment by arunoda** [comment]
Hmm. I can think of the issue since we removed the use of jquery.
@VladShcherbin could you see what went wrong?

**Comment by vladshcherbin** [comment]
JQuery spoiled me and google shows me some crap :(

@arunoda Fixed in the PR. Sorry.

**Comment by arunoda** [comment]
Try the latest version. (1.3.1)

**Comment by moooji** [comment]
Confirmed, works great in Safari now!
