### ISSUE TITLE
Duplicated Meta Tags

### ISSUE THREAD

**Issue by dyaa** [kadirahq/meteor-dochead#26]
Hello,

I'm using Dochead with [Urigo/angular-meteor](https://github.com/Urigo/angular-meteor) and i have an issue with `DocHead.addMeta` it append the meta Tags instead of replace it.

How can avoid that append!

fixes dyaa/deeMeteor#6

![desctop screenshot](https://cloud.githubusercontent.com/assets/4283185/11470702/86d2f3e4-9768-11e5-9927-f923d4bd9009.png)

**Comment by arunoda** [comment]
Call this for every route change: https://github.com/kadirahq/meteor-dochead/blob/master/lib/both.js#L79

**Comment by arunoda** [comment]
Some more information: https://github.com/kadirahq/meteor-dochead#docheadremovedocheadaddedtags

**Comment by dyaa** [comment]
Thank you :)

**Comment by dyaa** [comment]
Just adding this for other folks who are looking for the same issue.

``` js
angular.module("app").run(function ($rootScope, $state) {
    $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams){
        const elements = document.querySelectorAll('[dochead="1"]');
        // We use for-of here to loop only over iterable objects
        for (let element of elements) {
            element.parentNode.removeChild(element);
        }
    });
});
```
