### ISSUE TITLE
Cant get Dochead to work?

### ISSUE THREAD

**Issue by payner35** [kadirahq/meteor-dochead#29]
Im sure this is a basic problem.. but i cant get dochead to work at all?

I have tried to add it in a component... in a container.. in a componentDidMount etc..

```
import { DocHead } from 'meteor/kadira:dochead';

DocHead.setTitle("Some title");
```

i view source.. and do not see the meta. 

Do i need Spiderable / phantom.js to make this work?

Im using Mantra.. not using Flow-Router SSR

**Comment by arunoda** [comment]
If it's with phantomjs this is rendered dynamically. You can see it with the view-source. But with inspect elements.

**Comment by arunoda** [comment]
If it's FlowRouter SSR, then you should do it someplace other than `componentDidMount`. That hook never runs in the server.

**Comment by payner35** [comment]
So I must use Spiderable package to make this work..   (unless FlowRouter SSR)

**Comment by arunoda** [comment]
@payner35 yep.

**Comment by rjakobsson** [comment]
Would this work with prerender.io?

**Comment by payner35** [comment]
ya... should do.. prerender works the same way as spiderable I believe.
